apiVersion: 1

datasources:
  - name: influxdb-flux
    type: influxdb
    access: proxy
    orgId: 1
    url: http://$DOCKER_INFLUXDB_INIT_HOST:$DOCKER_INFLUXDB_INIT_PORT
    basicAuth: false
    isDefault: true
    user: $DOCKER_INFLUXDB_INIT_USERNAME
    secureJsonData:
      token: $DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
      password: $DOCKER_INFLUXDB_INIT_PASSWORD
    jsonData:
      version: Flux
      organization: $DOCKER_INFLUXDB_INIT_ORG
      defaultBucket: $DOCKER_INFLUXDB_INIT_BUCKET
