version: "3"

networks:
  temp-net:
    name: temp-net
    driver: bridge

services:
  influxdb:
    image: influxdb:2.6
    ports:
      - "8087:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: on-failure:10
    networks:
      - temp-net


  telegraf:
    image: telegraf:1.19
    ports:
      - '8125:8125/udp'
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
      - ./sample-metrics.in:/etc/telegraf/sample-metrics.in
    env_file:
      - .env
    depends_on:
      - influxdb
    networks:
      - temp-net

  grafana:
    env_file:
      - .env
    image: grafana/grafana-oss:8.5.15
    volumes:
      - grafana-storage:/var/lib/grafana:rw
      - ./grafana/conf/grafana.ini:/etc/grafana/grafana.ini:rw
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
    depends_on:
      - influxdb
    ports:
      - ${GRAFANA_PORT}:3000
    networks:
      - temp-net

volumes:
  grafana-storage:
  influxdb-storage:
